name: flexiv_dual_rgb_dp30
task_name: flexiv_dual_rgb_dp30
crop_shape: null

shape_meta:
  obs:
    rgb_head:
      shape: [3, 240, 424]
      type: rgb
    rgb_left_wrist:
      shape: [3, 240, 424]
      type: rgb
    rgb_right_wrist:
      shape: [3, 240, 424]
      type: rgb
    agent_pos:
      shape: [26]
      type: low_dim
  action:
    shape: [24]

env_runner: null

dataset:
  _target_: rl_100.dataset.flexiv_dual_rgb_dataset.FlexivDualRGBDataset
  zarr_path: data/flexiv_dual_rgb_dp30.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: ${training.seed}
  val_ratio: 0.02
  max_train_episodes: null
  sequence_stride: 1
  load_to_memory: false
  return_transitions: false
